#!/usr/bin/env python3
"""Generate every paper-table row and figure datapoint programmatically.

ART (SemPointer paper-rewrite swarm). Reads ONLY:
  experiments/results/final_{ruler,longbench,locomo,kvcompare}/metrics.json
  experiments/results/stats.json
  experiments/results/error_breakdown.json + config_table.json
  experiments/sempointer/cost_model.py  (analytic regime map; no numeric inputs)

Writes (idempotent overwrite):
  tables/N1_main_results.tex   suite summary (RULER / LongBench / LoCoMo)
  tables/N4_kv_pilot.tex       kv_compare pilot (n=10) small table
  tables/N2_ruler_pertask.tex  per-task RULER means x systems
  tables/N3_efficiency.tex     active tokens / latency / VRAM + ratios vs full
  tables/N5_failure_taxonomy.tex  miss taxonomy counts per suite
  figures/N1_pareto.pdf + .png   accuracy vs active tokens, 1 panel/suite
  figures/N2_ruler_bars.pdf      per-task grouped bars, Wilson-95 whiskers
  figures/N3_efficiency.pdf      latency + VRAM grouped bars per suite
  figures/N4_regime.pdf          analytic (N, m) regime map + measured points

CPU-only, no model inference. Rerun: experiments/warden/bin/python
experiments/make_paper_artifacts.py   (target < 5 min; typically < 30 s).
"""
import json
import math
import os
import sys
import time

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE) if os.path.basename(HERE) == "experiments" else HERE
# Script lives at <root>/experiments/make_paper_artifacts.py -> ROOT is repo root.
if os.path.basename(HERE) == "experiments":
    ROOT = os.path.dirname(HERE)
else:  # fallback: locate repo root by tables/ dir
    ROOT = HERE
RES = os.path.join(ROOT, "experiments", "results")
TAB = os.path.join(ROOT, "tables")
FIG = os.path.join(ROOT, "figures")

sys.path.insert(0, os.path.join(ROOT, "experiments"))
from sempointer.cost_model import SemPointerCostModel  # noqa: E402

SUITES_MAIN = ["final_ruler", "final_longbench", "final_locomo"]
SUITE_LABEL = {
    "final_ruler": "RULER",
    "final_longbench": "LongBench",
    "final_locomo": "LoCoMo",
    "final_kvcompare": "KV-compress pilot",
}
METRIC_LABEL = {
    "final_ruler": "RULER containment",
    "final_longbench": "LongBench F1",
    "final_locomo": "LoCoMo (token-F1 adaptation)",
    "final_kvcompare": "containment (pilot)",
}
SYS_ORDER_MAIN = ["sempointer", "full", "rag", "bm25"]
SYS_LABEL = {
    "sempointer": "SemPointer",
    "full": "Full context",
    "rag": "RAG",
    "bm25": "BM25",
}
RULER_TASKS = ["niah_single_1", "niah_single_2", "niah_single_3",
               "niah_multikey_1", "vt", "cwe"]

GAPS = []  # data gaps collected during generation


def load(name):
    with open(os.path.join(RES, name)) as f:
        return json.load(f)


def tex_escape(s):
    return str(s).replace("_", r"\_").replace("%", r"\%")


def f2(x):
    return f"{x:.4f}" if isinstance(x, float) else str(x)


def ci_str(ci):
    return f"[{ci[0]:.4f}, {ci[1]:.4f}]"


def wilson95(p, n, z=1.96):
    """Wilson 95% interval computed in-script from (cell mean, n)."""
    if n == 0:
        return (float("nan"), float("nan"))
    denom = 1.0 + z * z / n
    c = p + z * z / (2.0 * n)
    m = z * math.sqrt(p * (1.0 - p) / n + z * z / (4.0 * n * n))
    return ((c - m) / denom, (c + m) / denom)


def main():
    t0 = time.time()
    os.makedirs(TAB, exist_ok=True)
    os.makedirs(FIG, exist_ok=True)

    metrics = {s: load(f"{s}/metrics.json") for s in
               ["final_ruler", "final_longbench", "final_locomo", "final_kvcompare"]}
    stats = load("stats.json")
    errors = load("error_breakdown.json")
    config = load("config_table.json")

    # Model constants: k, m, block_size from config_table.json (measured config),
    # d / L_Q / B_res from cost_model defaults (read off a default instance).
    k_cfg = config["k"]
    m_cfg = config["m"]
    bs_cfg = config["block_size"]
    _default_model = SemPointerCostModel()
    d_cfg, lq_cfg = _default_model.d, _default_model.L_Q

    # ---------------- N1: main results ----------------
    oom = stats.get("oom_sensitivity", {})
    lb_full = oom.get("longbench_full_overall", {})
    lb_narr = oom.get("longbench_full_narrativeqa", {})
    n_oom = lb_narr.get("n_oom_missing", "?")
    mean_scored = lb_full.get("mean_scored_only", float("nan"))
    mean_zero = lb_full.get("mean_including_errors_as_zero", float("nan"))
    n1 = ["% AUTO-GENERATED by experiments/make_paper_artifacts.py — do not hand-edit.",
          r"\begin{table*}[t]",
          r"\centering",
          r"\caption{Main results: suite means with 95\% bootstrap CIs "
          r"(\texttt{metrics.json}; deltas/p-values in \texttt{stats.json}). "
          + " ".join(
              f"{SUITE_LABEL[s]} n={metrics[s]['systems']['sempointer']['n_scored']} "
              f"(full n={metrics[s]['systems']['full']['n_scored']});"
              for s in SUITES_MAIN) +
          r" Latency/VRAM cells are mean latency / mean peak VRAM. "
          f"LongBench full n=1136 vs 1150: {n_oom} narrativeqa "
          f"OOMs excluded (scored-only {mean_scored:.4f} vs errors-as-zero {mean_zero:.4f}, "
          f"favoring full). "
          r"KV-compress pilot (Table~N4, n=10) not pooled.}",
          r"\label{tab:N1-main}",
          r"\begin{tabular}{lllccccc}",
          r"\hline",
          r"Suite & Metric & System & $n$ & Score mean & 95\% CI & Active tok. & Latency (ms) / VRAM (MB) \\",
          r"\hline"]
    for s in SUITES_MAIN:
        for i, sys in enumerate(SYS_ORDER_MAIN):
            d = metrics[s]["systems"][sys]
            suite_cell = SUITE_LABEL[s] if i == 0 else ""
            n1.append(
                f"{suite_cell} & {METRIC_LABEL[s] if i == 0 else ''} & {SYS_LABEL[sys]} & "
                f"{d['n_scored']} & {f2(d['score_mean'])} & {ci_str(d['score_ci95'])} & "
                f"{d['active_tokens_mean']:.1f} & {d['latency_ms_mean']:.1f} / {d['peak_vram_mb_mean']:.1f} \\\\")
        n1.append(r"\hline")
    n1 += [r"\end{tabular}", r"\end{table*}", ""]
    with open(os.path.join(TAB, "N1_main_results.tex"), "w") as f:
        f.write("\n".join(n1))

    # ---------------- N4: kv pilot ----------------
    kvm = metrics["final_kvcompare"]["systems"]
    kv_order = ["sempointer", "full", "kvpress_snapkv_0.3", "kvpress_tova_0.3", "kvpress_knorm_0.3"]
    kv_labels = {"sempointer": "SemPointer", "full": "Full context",
                 "kvpress_snapkv_0.3": "KVPress SnapKV 0.3",
                 "kvpress_tova_0.3": "KVPress ToVA 0.3",
                 "kvpress_knorm_0.3": "KVPress KNorm 0.3"}
    pilot_note = stats.get("suites", {}).get("final_kvcompare", {}).get(
        "pilot_note", "kv_compare n=10 pilot; CIs wide; no significance claimed.")
    n4 = ["% AUTO-GENERATED by experiments/make_paper_artifacts.py — do not hand-edit.",
          r"\begin{table}[t]",
          r"\centering",
          r"\caption{KV-compress pilot (n=10, containment). CIs wide; no significance claimed.}",
          r"\label{tab:N4-kv-pilot}",
          r"\begin{tabular}{lcccc}",
          r"\hline",
          r"System & $n$ & Score mean & 95\% CI & Active tok. / Latency (ms) / VRAM (MB) \\",
          r"\hline"]
    for sys in kv_order:
        if sys not in kvm:
            GAPS.append(f"final_kvcompare missing system {sys}")
            continue
        d = kvm[sys]
        n4.append(
            f"{kv_labels[sys]} & {d['n_scored']} & {f2(d['score_mean'])} & {ci_str(d['score_ci95'])} & "
            f"{d['active_tokens_mean']:.1f} / {d['latency_ms_mean']:.1f} / {d['peak_vram_mb_mean']:.1f} \\\\")
    n4 += [r"\hline", r"\end{tabular}", r"\end{table}", ""]
    with open(os.path.join(TAB, "N4_kv_pilot.tex"), "w") as f:
        f.write("\n".join(n4))

    # ---------------- N2: RULER per-task ----------------
    rm = metrics["final_ruler"]["systems"]
    for t in RULER_TASKS:  # gap check
        for sys in SYS_ORDER_MAIN:
            cell = rm[sys].get("per_task", {}).get(t)
            if cell is None or cell.get("n") != 30:
                GAPS.append(f"RULER per-task cell {sys}/{t}: {cell}")
    n2 = ["% AUTO-GENERATED by experiments/make_paper_artifacts.py — do not hand-edit.",
          r"\begin{table*}[t]",
          r"\centering",
          r"\caption{RULER per-task means ($n=30$/cell). Tasks: "
          r"\texttt{niah\_single\_1/2/3}, \texttt{multikey\_1}, \texttt{vt}, \texttt{cwe} "
          r"(see Methods). Per-task CIs not stored (suite CIs only); Fig.~N2 shows Wilson-95 "
          r"whiskers from cell means. Sparse systems collapse on vt/cwe; full keeps a large vt margin.}",
          r"\label{tab:N2-ruler-pertask}",
          r"\begin{tabular}{lcccccc}",
          r"\hline",
          r"System & niah\_single\_1 & niah\_single\_2 & niah\_single\_3 & multikey\_1 & vt & cwe \\",
          r"\hline"]
    for sys in SYS_ORDER_MAIN:
        cells = []
        for t in RULER_TASKS:
            c = rm[sys]["per_task"][t]
            cells.append(f"{c['score_mean']:.3f} ({c['n']})")
        n2.append(f"{SYS_LABEL[sys]} & " + " & ".join(cells) + r" \\")
    n2 += [r"\hline", r"\end{tabular}", r"\end{table*}", ""]
    with open(os.path.join(TAB, "N2_ruler_pertask.tex"), "w") as f:
        f.write("\n".join(n2))

    # ---------------- N3: efficiency (+ ratios vs full, computed in-script) ----------------
    n3 = ["% AUTO-GENERATED by experiments/make_paper_artifacts.py — do not hand-edit.",
          r"\begin{table*}[t]",
          r"\centering",
          r"\caption{Efficiency means with sparse/full ratios vs full computed in-script "
          r"($<$1 favors sparse).}",
          r"\label{tab:N3-efficiency}",
          r"\begin{tabular}{llcccccc}",
          r"\hline",
          r"Suite & System & Active tok. & Latency (ms) & VRAM (MB) & Tok ratio & Lat ratio & VRAM ratio \\",
          r"\hline"]
    for s in SUITES_MAIN:
        full = metrics[s]["systems"]["full"]
        for i, sys in enumerate(SYS_ORDER_MAIN):
            d = metrics[s]["systems"][sys]
            rt = d["active_tokens_mean"] / full["active_tokens_mean"]
            rl = d["latency_ms_mean"] / full["latency_ms_mean"]
            rv = d["peak_vram_mb_mean"] / full["peak_vram_mb_mean"]
            n3.append(
                f"{SUITE_LABEL[s] if i == 0 else ''} & {SYS_LABEL[sys]} & "
                f"{d['active_tokens_mean']:.1f} & {d['latency_ms_mean']:.1f} & "
                f"{d['peak_vram_mb_mean']:.1f} & {rt:.3f} & {rl:.3f} & {rv:.3f} \\\\")
        n3.append(r"\hline")
    n3 += [r"\end{tabular}", r"\end{table*}", ""]
    with open(os.path.join(TAB, "N3_efficiency.tex"), "w") as f:
        f.write("\n".join(n3))

    # ---------------- N5: failure taxonomy ----------------
    miss_thr = errors.get("miss_threshold", {})
    thr_txt = (f"Miss: score$<$1.0 (containment) or $<$0.5 (F1); "
               f"retrieval-miss: miss with selected\\_ids $\\cap$ gold\\_blocks $=\\emptyset$.")
    n5 = ["% AUTO-GENERATED by experiments/make_paper_artifacts.py — do not hand-edit.",
          r"\begin{table*}[t]",
          r"\centering",
          r"\caption{Miss taxonomy per suite (\texttt{error\_breakdown.json}). " + thr_txt +
          r" \texttt{block-hit-wrong}: gold selected but answer wrong; "
          r"\texttt{unlocalizable}: answer unlocalizable under chunking rule; "
          r"\texttt{error-row}: \texttt{n\_errors}. Full misses are NA (no retrieval attribution).}",
          r"\label{tab:N5-taxonomy}",
          r"\begin{tabular}{lllcccccc}",
          r"\hline",
          r"Suite & System & $n$ & Hit & Miss & Retrieval-miss & Block-hit-wrong / NA & Unlocalizable & Error-row \\",
          r"\hline"]
    for s in SUITES_MAIN + ["final_kvcompare"]:
        suite_label = SUITE_LABEL[s] + (" (pilot n=10)" if s == "final_kvcompare" else "")
        by_sys = errors.get("suites", {}).get(s, {}).get("by_system", {})
        if not by_sys:
            GAPS.append(f"error_breakdown.json has no by_system for {s}")
            continue
        order = SYS_ORDER_MAIN if s != "final_kvcompare" else kv_order
        for i, sys in enumerate(order):
            c = by_sys.get(sys)
            mm = metrics[s]["systems"].get(sys, {})
            if c is None:
                GAPS.append(f"error_breakdown.json missing {s}/{sys}")
                continue
            if "block-hit-wrong-answer" in c:
                bhw, tag = c["block-hit-wrong-answer"], ""
            elif "miss-full-or-kvpress-attribution-NA" in c:
                bhw, tag = c["miss-full-or-kvpress-attribution-NA"], " (NA)"
            else:
                bhw, tag = 0, ""
            n5.append(
                f"{suite_label if i == 0 else ''} & {tex_escape(kv_labels.get(sys, SYS_LABEL.get(sys, sys)))} & "
                f"{c.get('n_scored', mm.get('n_scored', '?'))} & {c.get('hit', 0)} & "
                f"{c.get('miss_total', 0)} & {c.get('retrieval-miss', 0)} & "
                f"{bhw}{tag} & {c.get('gold-not-localizable', 0)} & {mm.get('n_errors', '?')} \\\\")
        n5.append(r"\hline")
    n5 += [r"\end{tabular}", r"\end{table*}", ""]
    with open(os.path.join(TAB, "N5_failure_taxonomy.tex"), "w") as f:
        f.write("\n".join(n5))

    # ---------------- Figures ----------------
    plt.rcParams.update({"font.size": 9, "axes.labelsize": 9, "xtick.labelsize": 8,
                         "ytick.labelsize": 8, "legend.fontsize": 7.5, "figure.dpi": 150})
    PDF_META = {"CreationDate": None, "Creator": "experiments/make_paper_artifacts.py",
                "Producer": "matplotlib (deterministic)"}
    PDF_KW = {"metadata": PDF_META}
    colors = {"sempointer": "#1f77b4", "full": "#d62728", "rag": "#2ca02c", "bm25": "#ff7f0e"}
    markers = {"sempointer": "o", "full": "s", "rag": "^", "bm25": "D"}

    # N1 pareto: 1 panel per suite
    fig, axes = plt.subplots(1, 3, figsize=(7.2, 3.0))
    panel_title = {"final_ruler": "RULER (containment)",
                   "final_longbench": "LongBench (F1)",
                   "final_locomo": "LoCoMo (token-F1 adapt.)"}
    for ax, s in zip(axes, SUITES_MAIN):
        for sys in SYS_ORDER_MAIN:
            d = metrics[s]["systems"][sys]
            lo, hi = d["score_ci95"]
            ax.errorbar(d["active_tokens_mean"], d["score_mean"],
                        yerr=[[d["score_mean"] - lo], [hi - d["score_mean"]]],
                        fmt=markers[sys], color=colors[sys], capsize=3, ms=5,
                        label=SYS_LABEL[sys])
        ax.set_xscale("log")
        ax.set_xlabel("Active tokens (log)")
        ax.set_title(panel_title[s], fontsize=9)
    axes[0].set_ylabel("Score mean (95% CI)")
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncols=4, frameon=True)
    fig.suptitle("N1: accuracy vs active tokens (error bars = 95% CIs from metrics.json)")
    fig.tight_layout(rect=(0, 0.08, 1, 0.92))
    fig.savefig(os.path.join(FIG, "N1_pareto.pdf"), **PDF_KW)
    fig.savefig(os.path.join(FIG, "N1_pareto.png"))
    plt.close(fig)

    # N2 ruler grouped bars + Wilson-95 whiskers (computed in-script; per-task CIs not stored)
    x = np.arange(len(RULER_TASKS))
    w = 0.2
    fig, ax = plt.subplots(figsize=(7.2, 2.8))
    for j, sys in enumerate(SYS_ORDER_MAIN):
        means, lo_e, hi_e = [], [], []
        for t in RULER_TASKS:
            c = rm[sys]["per_task"][t]
            lo, hi = wilson95(c["score_mean"], c["n"])
            means.append(c["score_mean"])
            lo_e.append(c["score_mean"] - lo)
            hi_e.append(hi - c["score_mean"])
        ax.bar(x + (j - 1.5) * w, means, w, yerr=[lo_e, hi_e], capsize=2,
               color=colors[sys], label=SYS_LABEL[sys])
    ax.set_xticks(x)
    ax.set_xticklabels(["single\\_1", "single\\_2", "single\\_3", "multikey\\_1", "vt", "cwe"])
    ax.set_ylabel("Containment mean (n=30/cell)")
    ax.set_title("N2: RULER per-task means (whiskers = Wilson-95 from cell mean, n=30)")
    ax.legend(ncols=4, frameon=True)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "N2_ruler_bars.pdf"), **PDF_KW)
    plt.close(fig)

    # N3 efficiency: latency + VRAM grouped bars per suite
    suites_eff, sys_eff = SUITES_MAIN, SYS_ORDER_MAIN
    x = np.arange(len(suites_eff))
    w = 0.2
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 2.8))
    for ax, key, title in zip(axes,
                              ["latency_ms_mean", "peak_vram_mb_mean"],
                              ["Latency (ms, mean)", "Peak VRAM (MB, mean)"]):
        for j, sys in enumerate(sys_eff):
            vals = [metrics[s]["systems"][sys][key] for s in suites_eff]
            ax.bar(x + (j - 1.5) * w, vals, w, color=colors[sys], label=SYS_LABEL[sys])
        ax.set_xticks(x)
        ax.set_xticklabels([SUITE_LABEL[s] for s in suites_eff])
        ax.set_title(title)
    axes[0].set_ylabel("Mean")
    axes[0].legend(frameon=True)
    fig.suptitle("N3: efficiency means per suite (active tokens in Table N3)")
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "N3_efficiency.pdf"), **PDF_KW)
    plt.close(fig)

    # N4 regime map over (N, m) from cost model + measured operating points
    N_grid = np.arange(1, 65)
    m_grid = np.arange(0, 9)
    Kcap = 10
    Z = np.zeros((len(m_grid), len(N_grid)))
    for i, mm in enumerate(m_grid):
        for j, NN in enumerate(N_grid):
            mdl = SemPointerCostModel(d=d_cfg, B=bs_cfg, k=k_cfg, m=int(mm),
                                      B_res=bs_cfg, L_Q=lq_cfg,
                                      generator_class="pooling", substrate="M_text")
            ki = mdl.crossover_k_empirical(int(NN), max_K=Kcap)
            Z[i, j] = ki if ki is not None else (Kcap + 1)
    fig, ax = plt.subplots(figsize=(7.2, 3.2))
    im = ax.pcolormesh(N_grid, m_grid, Z, shading="nearest", vmin=1, vmax=Kcap + 1)
    cb = fig.colorbar(im, ax=ax)
    cb.set_label(f"Crossover queries K* (capped at {Kcap}+)")
    # Measured operating points: mean_n_blocks from config_table.json, m from config.
    # Labels staggered vertically to avoid overlap (all main suites sit at m=1).
    measured = [("final_ruler", "o", 4.2), ("final_longbench", "s", 2.4),
                ("final_locomo", "^", -1.8), ("final_kvcompare", "D", 1.6)]
    for s, mk, dy in measured:
        Nb = config.get("suites", {}).get(s, {}).get("mean_n_blocks_sempointer")
        if Nb is None:
            GAPS.append(f"config_table.json missing mean_n_blocks for {s}")
            continue
        ax.plot(Nb, m_cfg, marker=mk, ms=8, mec="white", mfc="black")
        ax.text(Nb + 0.7, m_cfg + dy, f"{SUITE_LABEL[s]} (N={Nb:.1f}, m={m_cfg})", fontsize=7.5,
                bbox=dict(fc="white", ec="none", alpha=0.7, pad=1))
    ax.plot([], [], "ko", ms=6, label="measured operating point")
    ax.set_xlabel("Blocks N")
    ax.set_ylabel("Resolved blocks m (feasible: m<=N)")
    ax.set_title(f"N4: analytic regime vs measured points\npooling, M_text, d={d_cfg}, "
                 f"B={bs_cfg}, k={k_cfg}, LQ={lq_cfg}")
    ax.legend(frameon=True, loc="upper right")
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "N4_regime.pdf"), **PDF_KW)
    plt.close(fig)

    # ---------------- verify ----------------
    expected = ["N1_main_results.tex", "N4_kv_pilot.tex", "N2_ruler_pertask.tex",
                "N3_efficiency.tex", "N5_failure_taxonomy.tex"]
    expected_fig = ["N1_pareto.pdf", "N1_pareto.png", "N2_ruler_bars.pdf",
                    "N3_efficiency.pdf", "N4_regime.pdf"]
    missing = [p for p in expected if not os.path.exists(os.path.join(TAB, p))]
    missing += [p for p in expected_fig if not os.path.exists(os.path.join(FIG, p))]
    dt = time.time() - t0
    print(f"rerun_time_s={dt:.1f}")
    print(f"tables_written={len(expected) - len([m for m in missing if m.endswith('.tex')])}/{len(expected)}")
    print(f"figures_written={len(expected_fig) - len([m for m in missing if not m.endswith('.tex')])}/{len(expected_fig)}")
    if GAPS:
        print("DATA_GAPS:")
        for g in GAPS:
            print(f"  - {g}")
    else:
        print("DATA_GAPS: none")
    if missing:
        print(f"MISSING: {missing}")
        sys.exit(1)
    print("OK: all 9+ outputs exist (5 tex + N1 pdf/png + N2/N3/N4 pdf).")


if __name__ == "__main__":
    main()
