"""Pilot multihop table generator (CPU-only, no model loads).

Reads experiments/results/pilot_multihop/metrics.json (v1: sempointer, full,
rag, bm25) and pilot_multihop_v2/metrics.json (v2: agentic_pointer,
iterative_rag, hybrid). Both pilots ran the SAME 30 musique examples on the
SAME model/seed/config, so cross-pilot comparison is matched-pair valid.
Writes tables/N6_pilot_multihop.tex. No hand-typed numbers.
"""

import json
import os

RESULTS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "results")
TABLES = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "tables")


def load(name):
    with open(os.path.join(RESULTS, name, "metrics.json")) as f:
        return json.load(f)


def main():
    v1 = load("pilot_multihop")
    v2 = load("pilot_multihop_v2")
    v3 = load("pilot_address")
    v4 = load("pilot_routing_v2")
    for v in (v2, v3, v4):
        assert v["engine"]["model_id"] == v1["engine"]["model_id"], "pilot model mismatch"
        assert v["n_examples"] == v1["n_examples"] == 30, "pilot n mismatch"
    # all pilots ran the same 30 musique examples: verify matched IDs
    def sys_ids(dirname, system):
        return sorted(
            r["example_id"] for r in
            map(json.loads, open(os.path.join(RESULTS, dirname, "predictions.jsonl")))
            if r["system"] == system)
    base = sys_ids("pilot_multihop", "sempointer")
    assert sys_ids("pilot_address", "sempointer") == base, "address pilot examples differ"
    assert sys_ids("pilot_routing_v2", "sempointer") == base, "routing pilot examples differ"
    assert sys_ids("pilot_routing_v2", "rag") == sys_ids("pilot_multihop", "rag")
    order = ["sempointer", "full", "rag", "bm25", "agentic_pointer",
             "agentic_pointer_v2", "iterative_rag", "hybrid", "address_rag"]
    merged = {**v1["systems"], **v2["systems"], **v3["systems"], **v4["systems"]}

    def fmt(x, nd=4):
        return f"{x:.{nd}f}"

    rows = []
    for s in order:
        d = merged[s]
        lo, hi = d["score_ci95"]
        name = s.replace("_", " ").title()
        rows.append(
            f"{name} & {d['n_scored']} & {fmt(d['score_mean'])} "
            f"& [{fmt(lo)}, {fmt(hi)}] & {d['active_tokens_mean']:.0f} "
            f"& {d['latency_ms_mean']:.0f} & {d['peak_vram_mb_mean']:.0f} \\\\"
        )

    body = "\n".join(rows)
    tex = (
        "% AUTO-GENERATED by experiments/pilot_table.py -- do not hand-edit.\n"
        "\\begin{table}[t]\n"
        "\\centering\n"
        "\\caption{Multi-hop pilot (LongBench musique, n=30 matched, "
        "Qwen2.5-3B-NF4, greedy, seed 42). Four pilots share same 30 examples/config, "
        "so nine arms comparable. "
        "CIs wide (n=30); no significance claimed. "
        "Session summary excluded (token-accounting defect).}\n"
        "\\label{tab:N6-pilot}\n"
        "\\begin{tabular}{lcccccc}\n"
        "\\toprule\n"
        "System & n & F1 mean & 95\\% CI & Active tok & Latency (ms) & VRAM (MB) \\\\\n"
        "\\midrule\n"
        f"{body}\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
        "\\end{table}\n"
    )
    out = os.path.join(TABLES, "N6_pilot_multihop.tex")
    with open(out, "w") as f:
        f.write(tex)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
