"""Build sempointer_lncs.tex (Springer LNCS proceedings) from sempointer_ieee.tex.

Usage: python3 build_lncs.py  (run from repo root)
Then:  tectonic sempointer_lncs.tex

Mechanical mapping only: no content edits. IEEE-specific constructs are
translated to LNCS equivalents; body prose/tables/figures are shared inputs.
"""
import re

SRC = "sempointer_ieee.tex"
DST = "sempointer_lncs.tex"

t = open(SRC).read()

# --- preamble: swap class, drop IEEE-only packages/commands ---
t = t.replace("\\documentclass[conference]{IEEEtran}\n\\IEEEoverridecommandlockouts",
              "\\documentclass[runningheads]{llncs}")
NEWTHM = (
    "% llncs predefines several theorem envs; define only the missing ones\n"
    "\\ifcsname definition\\endcsname\\else\\newtheorem{definition}{Definition}\\fi\n"
    "\\ifcsname axiom\\endcsname\\else\\newtheorem{axiom}{Axiom}\\fi\n"
    "\\ifcsname theorem\\endcsname\\else\\newtheorem{theorem}{Theorem}\\fi\n"
    "\\ifcsname proposition\\endcsname\\else\\newtheorem{proposition}{Proposition}\\fi\n"
    "\\ifcsname hypothesis\\endcsname\\else\\newtheorem{hypothesis}{Hypothesis}\\fi\n"
)
t = re.sub(
    r"\\newtheorem\{definition\}.*?\n\\newtheorem\{hypothesis\}\{Hypothesis\}\n",
    lambda _m: NEWTHM, t, flags=re.DOTALL)
t = t.replace("\\usepackage{amsmath,amssymb,amsfonts,amsthm}",
              "\\usepackage{amsmath,amssymb,amsfonts}")  # llncs defines proof itself
t = t.replace("\\usepackage{booktabs}",
              "\\usepackage{booktabs}\n\\usepackage{rotating}")  # sidewaystable
t = t.replace("\\bstctlcite{IEEEexample:BSTcontrol}\n\n", "")

# --- title block (line-based: \title ... \maketitle) ---
lines = t.split("\n")
i0 = next(i for i, l in enumerate(lines) if l.startswith("\\title{"))
i1 = next(i for i, l in enumerate(lines) if l.startswith("\\maketitle"))
lncs_title = [
    "\\title{SemPointer: Toward Random-Access Semantic Memory"
    " for Large Language Models}",
    "\\author{Viksit Garg\\inst{1}}",
    "\\institute{Department of Artificial Intelligence \\& Machine Learning,",
    "Dr. Akhilesh Das Gupta Institute of Professional Studies,",
    "New Delhi, India \\\\ \\email{viksitg427@gmail.com}}",
    "\\maketitle",
]
lines[i0:i1 + 1] = lncs_title
t = "\n".join(lines)

# --- keywords env ---
m = re.search(r"\\begin\{IEEEkeywords\}\n(.*?)\\end\{IEEEkeywords\}",
              t, re.DOTALL)
assert m, "IEEEkeywords not found"
kw = " \\and ".join(s.strip().rstrip(",") for s in m.group(1).strip().split(","))
t = t.replace(m.group(0), "\\keywords{" + kw + "}")

# --- floats: single-column class; N-tables use LNCS-sized variants ---
t = t.replace("\\begin{figure*}", "\\begin{figure}")
t = t.replace("\\end{figure*}", "\\end{figure}")
t = t.replace("\\begin{table*}", "\\begin{table}")
t = t.replace("\\end{table*}", "\\end{table}")
t = re.sub(r"\\input\{tables/(N\d+_[a-z_]+)\}",
           lambda m: "\\input{tables/LNCS_" + m.group(1) + "}", t)

# --- bibliography: replace the whole IEEE bib-tweak group (which wraps the
# --- \bibliographystyle/\bibliography commands) with the static LNCS bib
LNCSBIB = (
    "% static bibliography generated by gen_static_bib.py\n"
    "\\input{lncs_bibliography}"
)
t = re.sub(
    r"\\begingroup\n\\def\\IEEEbibitemsep.*?\n\\endgroup",
    lambda _m: LNCSBIB, t, flags=re.DOTALL)
t = re.sub(
    r"\\begingroup\n\\def\\IEEEbibitemsep.*?\n\\endgroup\n\n",
    "", t, flags=re.DOTALL)

open(DST, "w").write(t)
print(f"wrote {DST} ({len(t.splitlines())} lines)")
