"""Generate lncs_bibliography.tex (static thebibliography) from references.bib.

LNCS numeric style, sorted by first-author surname + year (splncs04 order).
Avoids any .bst/bibtex bundle dependency.

Usage: python3 gen_static_bib.py  (repo root)  ->  lncs_bibliography.tex
"""
import re

SRC = "references.bib"
DST = "lncs_bibliography.tex"


def split_entries(text):
    entries, depth, cur = [], 0, ""
    for line in text.splitlines():
        s = line.strip()
        if not cur and s.startswith("@"):
            cur = line + "\n"
            depth = line.count("{") - line.count("}")
            continue
        if cur:
            cur += line + "\n"
            depth += line.count("{") - line.count("}")
            if depth <= 0:
                entries.append(cur)
                cur = ""
    return entries


def fields(body):
    out, cur, depth, key = {}, "", 0, None
    i, n = 0, len(body)
    # split top-level key = value pairs
    start = 0
    parts, d, inq = [], 0, False
    for j, ch in enumerate(body):
        if ch == "{":
            d += 1
        elif ch == "}":
            d -= 1
        elif ch == "," and d == 0:
            parts.append(body[start:j])
            start = j + 1
    parts.append(body[start:])
    for p in parts:
        m = re.match(r"\s*([A-Za-z_]+)\s*=\s*(.*)\s*$", p, re.DOTALL)
        if not m:
            continue
        k, v = m.group(1).lower(), m.group(2).strip()
        if (v.startswith("{") and v.endswith("}")) or (
                v.startswith('"') and v.endswith('"')):
            v = v[1:-1]
        out[k] = " ".join(v.split())
    return out


def initials(name):
    toks = name.split()
    if not toks:
        return name
    surname = toks[-1]
    given = [t[0].upper() + "." for t in toks[:-1]
             if t[0].isalpha() and t not in ("von", "van", "de", "der")]
    return surname + ", " + "".join(given)


def fmt_authors(auth):
    names = [a.strip() for a in auth.split(" and ") if a.strip()]
    return ", ".join(initials(a) for a in names)


def clean_title(t):
    return t.replace("{", "").replace("}", "")


def fmt_entry(etype, key, f):
    au = fmt_authors(f.get("author", "Anonymous"))
    ti = clean_title(f.get("title", "Untitled"))
    yr = f.get("year", "n.d.")
    if etype == "article":
        ven = f.get("journal", "")
        extra = ""
        if f.get("volume"):
            extra += f", vol. {f['volume']}"
        if f.get("pages"):
            extra += f", pp. {f['pages'].replace('--', '--')}"
        tail = f"{ven}{extra} ({yr})."
    elif etype == "book":
        pub = f.get("publisher", "")
        tail = f"{pub} ({yr})." if pub else f"({yr})."
    else:  # inproceedings etc.
        ven = f.get("booktitle", "")
        extra = ""
        if f.get("volume"):
            extra += f", vol. {f['volume']}"
        if f.get("pages"):
            extra += f", pp. {f['pages']}"
        tail = f"In: {ven}{extra} ({yr})."
    url = f.get("url", "")
    if url:
        tail += f" {url}"
    return f"\\bibitem{{{key}}}\n{au}: {ti}. {tail}\n"


def sortkey(item):
    etype, key, f = item
    first = f.get("author", "").split(" and ")[0].strip().split()
    return ((first[-1] if first else "").lower(), f.get("year", ""), key)


def main():
    text = open(SRC).read()
    items = []
    for e in split_entries(text):
        m = re.match(r"@(\w+)\{([^,]+),(.*)\}\s*$", e, re.DOTALL)
        if not m:
            continue
        etype, key, body = m.group(1).lower(), m.group(2).strip(), m.group(3)
        if etype.startswith("ieeetranbstctl"):
            continue
        items.append((etype, key, fields(body)))
    items.sort(key=sortkey)
    out = ["% AUTO-GENERATED by gen_static_bib.py -- do not hand-edit.",
           "\\begin{thebibliography}{99}", ""]
    for etype, key, f in items:
        out.append(fmt_entry(etype, key, f))
    out.append("\\end{thebibliography}")
    open(DST, "w").write("\n".join(out) + "\n")
    print(f"wrote {DST} with {len(items)} entries")


if __name__ == "__main__":
    main()
