"""Generate tables/LNCS_*.tex variants from tables/N*.tex for the single-column
LNCS layout: table* -> table, footnotesize + tight tabcolsep. Same numbers,
no hand edits.

Usage: python3 lncs_tables.py  (repo root)
"""
import glob
import os
import re

TABLES = "tables"

# wide tables go landscape; the rest get scriptsize + tight columns
LANDSCAPE = {"N1_main_results", "N5_failure_taxonomy"}


def convert(name, src):
    t = open(src).read()
    base = os.path.basename(src)
    if base.startswith("LNCS_"):
        return None
    t = t.replace("\\begin{table*}[t]", "\\begin{table}[t]")
    t = t.replace("\\end{table*}", "\\end{table}")
    if name in LANDSCAPE:
        t = t.replace("\\begin{table}[t]", "\\begin{sidewaystable}")
        t = t.replace("\\end{table}", "\\end{sidewaystable}")
        size = ("\\centering\\footnotesize"
                "\\setlength{\\tabcolsep}{3pt}")
    else:
        size = ("\\centering\\scriptsize"
                "\\setlength{\\tabcolsep}{2pt}")
    t = t.replace("\\centering", size, 1)
    # shorten the auto-generated banner
    t = t.replace("AUTO-GENERATED by experiments/make_paper_artifacts.py",
                  "AUTO-GENERATED LNCS variant (see lncs_tables.py)")
    t = t.replace("AUTO-GENERATED by experiments/pilot_table.py",
                  "AUTO-GENERATED LNCS variant (see lncs_tables.py)")
    return t


def main():
    made = []
    for src in sorted(glob.glob(os.path.join(TABLES, "N*.tex"))):
        base = os.path.basename(src)
        if base.startswith("LNCS_"):
            continue
        name = base[:-4]
        body = convert(name, src)
        dst = os.path.join(TABLES, "LNCS_" + base)
        open(dst, "w").write(body)
        made.append(dst)
    print("wrote", len(made), "files:", ", ".join(sorted(made)))


if __name__ == "__main__":
    main()
